Stopping Using Exception Use Result Monad Instead